Repository learningequality/morango, pull requests merged in 2022-04, with the labels that each got.

#161 Eliminate extraneous queries for transfer session in buffer serialization
  CHANGELOG.md
  morango/__init__.py
  morango/models/core.py
  tests/testapp/tests/test_api.py
Labels: DEV: backend, TAG: performance

#162 Add an index to the Store partition field
  .pre-commit-config.yaml
  Makefile
  morango/migrations/0021_store_partition_index_create.py
  morango/models/core.py
  tests/testapp/tests/helpers.py
  tests/testapp/tests/test_migrations.py
Labels: TODO: needs review

#159 Defer foreign key checks for bulk processing during deserialization
  CHANGELOG.md
  morango/models/core.py
  morango/sync/backends/base.py
  morango/sync/backends/postgres.py
  morango/sync/backends/sqlite.py
  morango/sync/backends/utils.py
  morango/sync/operations.py
  tests/testapp/facility_profile/migrations/0002_auto_20220427_0449.py
  tests/testapp/facility_profile/models.py
  tests/testapp/tests/integration/test_syncsession.py
  tests/testapp/tests/sync/test_controller.py
  tests/testapp/tests/sync/test_operations.py
Labels: PR: needs review, DEV: backend, TAG: performance, TODO: needs review
